# -*- coding: utf-8 -*-
"""handling_calc_0533.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nn_cxjcw9Issf1lMbiptJ5YUYBBI9_eb
"""

class FormError(Exception):
  pass

def main_input(input_str):
  bagian_input = input_str.split()

  if len(bagian_input) != 3:
    raise FormError('Input Harus Terdiri dari 3 Element.')
  val1, op, val2 = bagian_input

  try:
    val1 = float(val1)
    val2 = float(val2)

  except ValueError:
    raise FormError('Elemen 1 dan Elemen 2 Harus Berupa Angka')

  if op not in ['+', '-', '/', '*']:
    raise FormError('Operator Tidak Sesuai')

  return val1, op, val2

def kalkulator(val1, op, val2):
  if op == '+':
    return val1 + val2
  elif op == '-':
    return val1 - val2
  elif op == '*':
    return val1 * val2
  elif op == '/':
    return val1 / val2

while True:
  print("""
  Contoh Penggunaan:
  1. Penjumlahan 1 + 2
  2. Pengurangan 5 - 3
  3. Perkalian 2 * 3
  4. Pembagian 6 / 3
  """)
  
  input_user = input('Masukkan Nilai: ')

  if input_user == 'exit':
    break

  try:
    val1, op, val2 = main_input(input_user)
    result = kalkulator(val1, op, val2)
    print(result)
    print("")

  except FormError as e:
    print(e)